# Generated by Django 5.2.7 on 2025-10-22 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_category_alter_book_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(upload_to='book_covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_link',
            field=models.FileField(upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.subcategory'),
        ),
    ]
