# Generated by Django 5.2.7 on 2025-11-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_cover_image_alter_book_pdf_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
