# Generated by Django 5.2.7 on 2025-11-14 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0004_book_is_trending'),
    ]

    operations = [
        migrations.CreateModel(
            name='EldergateLibraryUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('model_name', models.CharField(choices=[('Reader', 'Reader'), ('Librarian', 'Librarian'), ('Administrator', 'Administrator')], default='Reader', max_length=100)),
                ('reading_progress', models.IntegerField(default=0)),
                ('current_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='userLibrary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_type', models.CharField(blank=True, max_length=100, null=True)),
                ('time_read', models.DateTimeField(auto_now_add=True, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.eldergatelibraryuser')),
            ],
        ),
    ]
