# Generated by Django 5.2.7 on 2025-11-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlibrary',
            name='reading_progress',
            field=models.IntegerField(default=0),
        ),
    ]
