# Generated by Django 5.2.7 on 2025-11-14 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userlibrary_reading_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlibrary',
            name='reading_progress',
        ),
    ]
