# Generated by Django 5.2.7 on 2025-10-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_administrator_last_login_librarian_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='reader',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
