# Generated by Django 5.2.7 on 2025-10-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_administrator_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EldergateLibraryUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('model_name', models.CharField(choices=[('Reader', 'Reader'), ('Librarian', 'Librarian'), ('Administrator', 'Administrator')], default='Reader', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='Librarian',
        ),
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
